/* pnglibconf.h - library build configuration */

/* libpng version 1.6.2 - April 25, 2013 */

/* Copyright (c) 1998-2012 Glenn Randers-Pehrson */

/* This code is released under the libpng license. */
/* For conditions of distribution and use, see the disclaimer */
/* and license in png.h */

/* pnglibconf.h */
/* Machine generated file: DO NOT EDIT */
/* Derived from: scripts/pnglibconf.dfa */
#ifndef PNGLCONF_H
#define PNGLCONF_H
/* options */
#define PNG_16BIT_SUPPORTED
#define PNG_ALIGNED_MEMORY_SUPPORTED
/*#undef PNG_ARM_NEON_API_SUPPORTED
#undef PNG_ARM_NEON_CHECK_SUPPORTED
#undef PNG_ARM_NEON_SUPPORTED*/
#define PNG_BENIGN_ERRORS_SUPPORTED
#define PNG_BENIGN_READ_ERRORS_SUPPORTED
/*#undef PNG_BENIGN_WRITE_ERRORS_SUPPORTED*/
#define PNG_BUILD_GRAYSCALE_PALETTE_SUPPORTED
#define PNG_CHECK_FOR_INVALID_INDEX_SUPPORTED
#define PNG_COLORSPACE_SUPPORTED
#define PNG_CONSOLE_IO_SUPPORTED
#define PNG_CONVERT_tIME_SUPPORTED
#define PNG_EASY_ACCESS_SUPPORTED
/*#undef PNG_ERROR_NUMBERS_SUPPORTED*/
#define PNG_ERROR_TEXT_SUPPORTED
#define PNG_FIXED_POINT_SUPPORTED
#define PNG_FLOATING_ARITHMETIC_SUPPORTED
#define PNG_FLOATING_POINT_SUPPORTED
#define PNG_FORMAT_AFIRST_SUPPORTED
#define PNG_FORMAT_BGR_SUPPORTED
#define PNG_GAMMA_SUPPORTED
#define PNG_GET_PALETTE_MAX_SUPPORTED
#define PNG_HANDLE_AS_UNKNOWN_SUPPORTED
#define PNG_INCH_CONVERSIONS_SUPPORTED
#define PNG_INFO_IMAGE_SUPPORTED
#define PNG_IO_STATE_SUPPORTED
#define PNG_MNG_FEATURES_SUPPORTED
#define PNG_POINTER_INDEXING_SUPPORTED
#define PNG_PROGRESSIVE_READ_SUPPORTED
#define PNG_READ_16BIT_SUPPORTED
#define PNG_READ_ALPHA_MODE_SUPPORTED
#define PNG_READ_ANCILLARY_CHUNKS_SUPPORTED
#define PNG_READ_BACKGROUND_SUPPORTED
#define PNG_READ_BGR_SUPPORTED
#define PNG_READ_CHECK_FOR_INVALID_INDEX_SUPPORTED
#define PNG_READ_COMPOSITE_NODIV_SUPPORTED
#define PNG_READ_COMPRESSED_TEXT_SUPPORTED
#define PNG_READ_EXPAND_16_SUPPORTED
#define PNG_READ_EXPAND_SUPPORTED
#define PNG_READ_FILLER_SUPPORTED
#define PNG_READ_GAMMA_SUPPORTED
#define PNG_READ_GET_PALETTE_MAX_SUPPORTED
#define PNG_READ_GRAY_TO_RGB_SUPPORTED
#define PNG_READ_INTERLACING_SUPPORTED
#define PNG_READ_INT_FUNCTIONS_SUPPORTED
#define PNG_READ_INVERT_ALPHA_SUPPORTED
#define PNG_READ_INVERT_SUPPORTED
#define PNG_READ_OPT_PLTE_SUPPORTED
#define PNG_READ_PACKSWAP_SUPPORTED
#define PNG_READ_PACK_SUPPORTED
#define PNG_READ_QUANTIZE_SUPPORTED
#define PNG_READ_RGB_TO_GRAY_SUPPORTED
#define PNG_READ_SCALE_16_TO_8_SUPPORTED
#define PNG_READ_SHIFT_SUPPORTED
#define PNG_READ_STRIP_16_TO_8_SUPPORTED
#define PNG_READ_STRIP_ALPHA_SUPPORTED
#define PNG_READ_SUPPORTED
#define PNG_READ_SWAP_ALPHA_SUPPORTED
#define PNG_READ_SWAP_SUPPORTED
#define PNG_READ_TEXT_SUPPORTED
#define PNG_READ_TRANSFORMS_SUPPORTED
#define PNG_READ_UNKNOWN_CHUNKS_SUPPORTED
#define PNG_READ_USER_CHUNKS_SUPPORTED
#define PNG_READ_USER_TRANSFORM_SUPPORTED
#define PNG_READ_bKGD_SUPPORTED
#define PNG_READ_cHRM_SUPPORTED
#define PNG_READ_gAMA_SUPPORTED
#define PNG_READ_hIST_SUPPORTED
#define PNG_READ_iCCP_SUPPORTED
#define PNG_READ_iTXt_SUPPORTED
#define PNG_READ_oFFs_SUPPORTED
#define PNG_READ_pCAL_SUPPORTED
#define PNG_READ_pHYs_SUPPORTED
#define PNG_READ_sBIT_SUPPORTED
#define PNG_READ_sCAL_SUPPORTED
#define PNG_READ_sPLT_SUPPORTED
#define PNG_READ_sRGB_SUPPORTED
#define PNG_READ_tEXt_SUPPORTED
#define PNG_READ_tIME_SUPPORTED
#define PNG_READ_tRNS_SUPPORTED
#define PNG_READ_zTXt_SUPPORTED
/*#undef PNG_SAFE_LIMITS_SUPPORTED*/
#define PNG_SAVE_INT_32_SUPPORTED
#define PNG_SAVE_UNKNOWN_CHUNKS_SUPPORTED
#define PNG_SEQUENTIAL_READ_SUPPORTED
#define PNG_SETJMP_SUPPORTED
#define PNG_SET_CHUNK_CACHE_LIMIT_SUPPORTED
#define PNG_SET_CHUNK_MALLOC_LIMIT_SUPPORTED
/*#undef PNG_SET_OPTION_SUPPORTED*/
#define PNG_SET_UNKNOWN_CHUNKS_SUPPORTED
#define PNG_SET_USER_LIMITS_SUPPORTED
#define PNG_SIMPLIFIED_READ_AFIRST_SUPPORTED
#define PNG_SIMPLIFIED_READ_BGR_SUPPORTED
#define PNG_SIMPLIFIED_READ_SUPPORTED
#define PNG_SIMPLIFIED_WRITE_AFIRST_SUPPORTED
#define PNG_SIMPLIFIED_WRITE_BGR_SUPPORTED
#define PNG_SIMPLIFIED_WRITE_SUPPORTED
#define PNG_STDIO_SUPPORTED
#define PNG_STORE_UNKNOWN_CHUNKS_SUPPORTED
#define PNG_TEXT_SUPPORTED
#define PNG_TIME_RFC1123_SUPPORTED
#define PNG_UNKNOWN_CHUNKS_SUPPORTED
#define PNG_USER_CHUNKS_SUPPORTED
#define PNG_USER_LIMITS_SUPPORTED
#define PNG_USER_MEM_SUPPORTED
#define PNG_USER_TRANSFORM_INFO_SUPPORTED
#define PNG_USER_TRANSFORM_PTR_SUPPORTED
#define PNG_WARNINGS_SUPPORTED
#define PNG_WRITE_16BIT_SUPPORTED
#define PNG_WRITE_ANCILLARY_CHUNKS_SUPPORTED
#define PNG_WRITE_BGR_SUPPORTED
#define PNG_WRITE_CHECK_FOR_INVALID_INDEX_SUPPORTED
#define PNG_WRITE_COMPRESSED_TEXT_SUPPORTED
#define PNG_WRITE_CUSTOMIZE_ZTXT_COMPRESSION_SUPPORTED
#define PNG_WRITE_FILLER_SUPPORTED
#define PNG_WRITE_FILTER_SUPPORTED
#define PNG_WRITE_FLUSH_SUPPORTED
#define PNG_WRITE_GET_PALETTE_MAX_SUPPORTED
#define PNG_WRITE_INTERLACING_SUPPORTED
#define PNG_WRITE_INT_FUNCTIONS_SUPPORTED
#define PNG_WRITE_INVERT_ALPHA_SUPPORTED
#define PNG_WRITE_INVERT_SUPPORTED
#define PNG_WRITE_OPTIMIZE_CMF_SUPPORTED
#define PNG_WRITE_PACKSWAP_SUPPORTED
#define PNG_WRITE_PACK_SUPPORTED
#define PNG_WRITE_SHIFT_SUPPORTED
#define PNG_WRITE_SUPPORTED
#define PNG_WRITE_SWAP_ALPHA_SUPPORTED
#define PNG_WRITE_SWAP_SUPPORTED
#define PNG_WRITE_TEXT_SUPPORTED
#define PNG_WRITE_TRANSFORMS_SUPPORTED
#define PNG_WRITE_UNKNOWN_CHUNKS_SUPPORTED
#define PNG_WRITE_USER_TRANSFORM_SUPPORTED
#define PNG_WRITE_WEIGHTED_FILTER_SUPPORTED
#define PNG_WRITE_bKGD_SUPPORTED
#define PNG_WRITE_cHRM_SUPPORTED
#define PNG_WRITE_gAMA_SUPPORTED
#define PNG_WRITE_hIST_SUPPORTED
#define PNG_WRITE_iCCP_SUPPORTED
#define PNG_WRITE_iTXt_SUPPORTED
#define PNG_WRITE_oFFs_SUPPORTED
#define PNG_WRITE_pCAL_SUPPORTED
#define PNG_WRITE_pHYs_SUPPORTED
#define PNG_WRITE_sBIT_SUPPORTED
#define PNG_WRITE_sCAL_SUPPORTED
#define PNG_WRITE_sPLT_SUPPORTED
#define PNG_WRITE_sRGB_SUPPORTED
#define PNG_WRITE_tEXt_SUPPORTED
#define PNG_WRITE_tIME_SUPPORTED
#define PNG_WRITE_tRNS_SUPPORTED
#define PNG_WRITE_zTXt_SUPPORTED
#define PNG_bKGD_SUPPORTED
#define PNG_cHRM_SUPPORTED
#define PNG_gAMA_SUPPORTED
#define PNG_hIST_SUPPORTED
#define PNG_iCCP_SUPPORTED
#define PNG_iTXt_SUPPORTED
#define PNG_oFFs_SUPPORTED
#define PNG_pCAL_SUPPORTED
#define PNG_pHYs_SUPPORTED
#define PNG_sBIT_SUPPORTED
#define PNG_sCAL_SUPPORTED
#define PNG_sPLT_SUPPORTED
#define PNG_sRGB_SUPPORTED
#define PNG_tEXt_SUPPORTED
#define PNG_tIME_SUPPORTED
#define PNG_tRNS_SUPPORTED
#define PNG_zTXt_SUPPORTED
/* end of options */
/* settings */
#define PNG_API_RULE 0
#define PNG_CALLOC_SUPPORTED
#define PNG_COST_SHIFT 3
#define PNG_DEFAULT_READ_MACROS 1
#define PNG_GAMMA_THRESHOLD_FIXED 5000
#define PNG_IDAT_READ_SIZE PNG_ZBUF_SIZE
#define PNG_INFLATE_BUF_SIZE 1024
#define PNG_MAX_GAMMA_8 11
#define PNG_PREFIX png16_
#define PNG_QUANTIZE_BLUE_BITS 5
#define PNG_QUANTIZE_GREEN_BITS 5
#define PNG_QUANTIZE_RED_BITS 5
#define PNG_TEXT_Z_DEFAULT_COMPRESSION (-1)
#define PNG_TEXT_Z_DEFAULT_STRATEGY 0
#define PNG_WEIGHT_SHIFT 8
#define PNG_ZBUF_SIZE 8192
#define PNG_Z_DEFAULT_COMPRESSION (-1)
#define PNG_Z_DEFAULT_NOFILTER_STRATEGY 0
#define PNG_Z_DEFAULT_STRATEGY 1
#define PNG_sCAL_PRECISION 5
#define PNG_sRGB_PROFILE_CHECKS 2
/* end of settings */
#define png_access_version_number png16_png_access_version_number
#define png_benign_error png16_png_benign_error
#define png_build_grayscale_palette png16_png_build_grayscale_palette
#define png_calloc png16_png_calloc
#define png_chunk_benign_error png16_png_chunk_benign_error
#define png_chunk_error png16_png_chunk_error
#define png_chunk_warning png16_png_chunk_warning
#define png_convert_from_struct_tm png16_png_convert_from_struct_tm
#define png_convert_from_time_t png16_png_convert_from_time_t
#define png_convert_to_rfc1123 png16_png_convert_to_rfc1123
#define png_convert_to_rfc1123_buffer png16_png_convert_to_rfc1123_buffer
#define png_create_info_struct png16_png_create_info_struct
#define png_create_read_struct png16_png_create_read_struct
#define png_create_read_struct_2 png16_png_create_read_struct_2
#define png_create_write_struct png16_png_create_write_struct
#define png_create_write_struct_2 png16_png_create_write_struct_2
#define png_data_freer png16_png_data_freer
#define png_destroy_info_struct png16_png_destroy_info_struct
#define png_destroy_read_struct png16_png_destroy_read_struct
#define png_destroy_write_struct png16_png_destroy_write_struct
#define png_error png16_png_error
#define png_free png16_png_free
#define png_free_data png16_png_free_data
#define png_free_default png16_png_free_default
#define png_get_IHDR png16_png_get_IHDR
#define png_get_PLTE png16_png_get_PLTE
#define png_get_bKGD png16_png_get_bKGD
#define png_get_bit_depth png16_png_get_bit_depth
#define png_get_cHRM png16_png_get_cHRM
#define png_get_cHRM_XYZ png16_png_get_cHRM_XYZ
#define png_get_cHRM_XYZ_fixed png16_png_get_cHRM_XYZ_fixed
#define png_get_cHRM_fixed png16_png_get_cHRM_fixed
#define png_get_channels png16_png_get_channels
#define png_get_chunk_cache_max png16_png_get_chunk_cache_max
#define png_get_chunk_malloc_max png16_png_get_chunk_malloc_max
#define png_get_color_type png16_png_get_color_type
#define png_get_compression_buffer_size png16_png_get_compression_buffer_size
#define png_get_compression_type png16_png_get_compression_type
#define png_get_copyright png16_png_get_copyright
#define png_get_current_pass_number png16_png_get_current_pass_number
#define png_get_current_row_number png16_png_get_current_row_number
#define png_get_error_ptr png16_png_get_error_ptr
#define png_get_filter_type png16_png_get_filter_type
#define png_get_gAMA png16_png_get_gAMA
#define png_get_gAMA_fixed png16_png_get_gAMA_fixed
#define png_get_hIST png16_png_get_hIST
#define png_get_header_ver png16_png_get_header_ver
#define png_get_header_version png16_png_get_header_version
#define png_get_iCCP png16_png_get_iCCP
#define png_get_image_height png16_png_get_image_height
#define png_get_image_width png16_png_get_image_width
#define png_get_int_32 png16_png_get_int_32
#define png_get_interlace_type png16_png_get_interlace_type
#define png_get_io_chunk_type png16_png_get_io_chunk_type
#define png_get_io_ptr png16_png_get_io_ptr
#define png_get_io_state png16_png_get_io_state
#define png_get_libpng_ver png16_png_get_libpng_ver
#define png_get_mem_ptr png16_png_get_mem_ptr
#define png_get_oFFs png16_png_get_oFFs
#define png_get_pCAL png16_png_get_pCAL
#define png_get_pHYs png16_png_get_pHYs
#define png_get_pHYs_dpi png16_png_get_pHYs_dpi
#define png_get_palette_max png16_png_get_palette_max
#define png_get_pixel_aspect_ratio png16_png_get_pixel_aspect_ratio
#define png_get_pixel_aspect_ratio_fixed png16_png_get_pixel_aspect_ratio_fixed
#define png_get_pixels_per_inch png16_png_get_pixels_per_inch
#define png_get_pixels_per_meter png16_png_get_pixels_per_meter
#define png_get_progressive_ptr png16_png_get_progressive_ptr
#define png_get_rgb_to_gray_status png16_png_get_rgb_to_gray_status
#define png_get_rowbytes png16_png_get_rowbytes
#define png_get_rows png16_png_get_rows
#define png_get_sBIT png16_png_get_sBIT
#define png_get_sCAL png16_png_get_sCAL
#define png_get_sCAL_fixed png16_png_get_sCAL_fixed
#define png_get_sCAL_s png16_png_get_sCAL_s
#define png_get_sPLT png16_png_get_sPLT
#define png_get_sRGB png16_png_get_sRGB
#define png_get_signature png16_png_get_signature
#define png_get_tIME png16_png_get_tIME
#define png_get_tRNS png16_png_get_tRNS
#define png_get_text png16_png_get_text
#define png_get_uint_16 png16_png_get_uint_16
#define png_get_uint_31 png16_png_get_uint_31
#define png_get_uint_32 png16_png_get_uint_32
#define png_get_unknown_chunks png16_png_get_unknown_chunks
#define png_get_user_chunk_ptr png16_png_get_user_chunk_ptr
#define png_get_user_height_max png16_png_get_user_height_max
#define png_get_user_transform_ptr png16_png_get_user_transform_ptr
#define png_get_user_width_max png16_png_get_user_width_max
#define png_get_valid png16_png_get_valid
#define png_get_x_offset_inches png16_png_get_x_offset_inches
#define png_get_x_offset_inches_fixed png16_png_get_x_offset_inches_fixed
#define png_get_x_offset_microns png16_png_get_x_offset_microns
#define png_get_x_offset_pixels png16_png_get_x_offset_pixels
#define png_get_x_pixels_per_inch png16_png_get_x_pixels_per_inch
#define png_get_x_pixels_per_meter png16_png_get_x_pixels_per_meter
#define png_get_y_offset_inches png16_png_get_y_offset_inches
#define png_get_y_offset_inches_fixed png16_png_get_y_offset_inches_fixed
#define png_get_y_offset_microns png16_png_get_y_offset_microns
#define png_get_y_offset_pixels png16_png_get_y_offset_pixels
#define png_get_y_pixels_per_inch png16_png_get_y_pixels_per_inch
#define png_get_y_pixels_per_meter png16_png_get_y_pixels_per_meter
#define png_handle_as_unknown png16_png_handle_as_unknown
#define png_image_begin_read_from_file png16_png_image_begin_read_from_file
#define png_image_begin_read_from_memory png16_png_image_begin_read_from_memory
#define png_image_begin_read_from_stdio png16_png_image_begin_read_from_stdio
#define png_image_finish_read png16_png_image_finish_read
#define png_image_free png16_png_image_free
#define png_image_write_to_file png16_png_image_write_to_file
#define png_image_write_to_stdio png16_png_image_write_to_stdio
#define png_info_init_3 png16_png_info_init_3
#define png_init_io png16_png_init_io
#define png_longjmp png16_png_longjmp
#define png_malloc png16_png_malloc
#define png_malloc_default png16_png_malloc_default
#define png_malloc_warn png16_png_malloc_warn
#define png_permit_mng_features png16_png_permit_mng_features
#define png_process_data png16_png_process_data
#define png_process_data_pause png16_png_process_data_pause
#define png_process_data_skip png16_png_process_data_skip
#define png_progressive_combine_row png16_png_progressive_combine_row
#define png_read_end png16_png_read_end
#define png_read_image png16_png_read_image
#define png_read_info png16_png_read_info
#define png_read_png png16_png_read_png
#define png_read_row png16_png_read_row
#define png_read_rows png16_png_read_rows
#define png_read_update_info png16_png_read_update_info
#define png_reset_zstream png16_png_reset_zstream
#define png_save_int_32 png16_png_save_int_32
#define png_save_uint_16 png16_png_save_uint_16
#define png_save_uint_32 png16_png_save_uint_32
#define png_set_IHDR png16_png_set_IHDR
#define png_set_PLTE png16_png_set_PLTE
#define png_set_add_alpha png16_png_set_add_alpha
#define png_set_alpha_mode png16_png_set_alpha_mode
#define png_set_alpha_mode_fixed png16_png_set_alpha_mode_fixed
#define png_set_bKGD png16_png_set_bKGD
#define png_set_background png16_png_set_background
#define png_set_background_fixed png16_png_set_background_fixed
#define png_set_benign_errors png16_png_set_benign_errors
#define png_set_bgr png16_png_set_bgr
#define png_set_cHRM png16_png_set_cHRM
#define png_set_cHRM_XYZ png16_png_set_cHRM_XYZ
#define png_set_cHRM_XYZ_fixed png16_png_set_cHRM_XYZ_fixed
#define png_set_cHRM_fixed png16_png_set_cHRM_fixed
#define png_set_check_for_invalid_index png16_png_set_check_for_invalid_index
#define png_set_chunk_cache_max png16_png_set_chunk_cache_max
#define png_set_chunk_malloc_max png16_png_set_chunk_malloc_max
#define png_set_compression_buffer_size png16_png_set_compression_buffer_size
#define png_set_compression_level png16_png_set_compression_level
#define png_set_compression_mem_level png16_png_set_compression_mem_level
#define png_set_compression_method png16_png_set_compression_method
#define png_set_compression_strategy png16_png_set_compression_strategy
#define png_set_compression_window_bits png16_png_set_compression_window_bits
#define png_set_crc_action png16_png_set_crc_action
#define png_set_error_fn png16_png_set_error_fn
#define png_set_expand png16_png_set_expand
#define png_set_expand_16 png16_png_set_expand_16
#define png_set_expand_gray_1_2_4_to_8 png16_png_set_expand_gray_1_2_4_to_8
#define png_set_filler png16_png_set_filler
#define png_set_filter png16_png_set_filter
#define png_set_filter_heuristics png16_png_set_filter_heuristics
#define png_set_filter_heuristics_fixed png16_png_set_filter_heuristics_fixed
#define png_set_flush png16_png_set_flush
#define png_set_gAMA png16_png_set_gAMA
#define png_set_gAMA_fixed png16_png_set_gAMA_fixed
#define png_set_gamma png16_png_set_gamma
#define png_set_gamma_fixed png16_png_set_gamma_fixed
#define png_set_gray_to_rgb png16_png_set_gray_to_rgb
#define png_set_hIST png16_png_set_hIST
#define png_set_iCCP png16_png_set_iCCP
#define png_set_interlace_handling png16_png_set_interlace_handling
#define png_set_invalid png16_png_set_invalid
#define png_set_invert_alpha png16_png_set_invert_alpha
#define png_set_invert_mono png16_png_set_invert_mono
#define png_set_keep_unknown_chunks png16_png_set_keep_unknown_chunks
#define png_set_longjmp_fn png16_png_set_longjmp_fn
#define png_set_mem_fn png16_png_set_mem_fn
#define png_set_oFFs png16_png_set_oFFs
#define png_set_pCAL png16_png_set_pCAL
#define png_set_pHYs png16_png_set_pHYs
#define png_set_packing png16_png_set_packing
#define png_set_packswap png16_png_set_packswap
#define png_set_palette_to_rgb png16_png_set_palette_to_rgb
#define png_set_progressive_read_fn png16_png_set_progressive_read_fn
#define png_set_quantize png16_png_set_quantize
#define png_set_read_fn png16_png_set_read_fn
#define png_set_read_status_fn png16_png_set_read_status_fn
#define png_set_read_user_chunk_fn png16_png_set_read_user_chunk_fn
#define png_set_read_user_transform_fn png16_png_set_read_user_transform_fn
#define png_set_rgb_to_gray png16_png_set_rgb_to_gray
#define png_set_rgb_to_gray_fixed png16_png_set_rgb_to_gray_fixed
#define png_set_rows png16_png_set_rows
#define png_set_sBIT png16_png_set_sBIT
#define png_set_sCAL png16_png_set_sCAL
#define png_set_sCAL_fixed png16_png_set_sCAL_fixed
#define png_set_sCAL_s png16_png_set_sCAL_s
#define png_set_sPLT png16_png_set_sPLT
#define png_set_sRGB png16_png_set_sRGB
#define png_set_sRGB_gAMA_and_cHRM png16_png_set_sRGB_gAMA_and_cHRM
#define png_set_scale_16 png16_png_set_scale_16
#define png_set_shift png16_png_set_shift
#define png_set_sig_bytes png16_png_set_sig_bytes
#define png_set_strip_16 png16_png_set_strip_16
#define png_set_strip_alpha png16_png_set_strip_alpha
#define png_set_swap png16_png_set_swap
#define png_set_swap_alpha png16_png_set_swap_alpha
#define png_set_tIME png16_png_set_tIME
#define png_set_tRNS png16_png_set_tRNS
#define png_set_tRNS_to_alpha png16_png_set_tRNS_to_alpha
#define png_set_text png16_png_set_text
#define png_set_text_compression_level png16_png_set_text_compression_level
#define png_set_text_compression_mem_level png16_png_set_text_compression_mem_level
#define png_set_text_compression_method png16_png_set_text_compression_method
#define png_set_text_compression_strategy png16_png_set_text_compression_strategy
#define png_set_text_compression_window_bits png16_png_set_text_compression_window_bits
#define png_set_unknown_chunk_location png16_png_set_unknown_chunk_location
#define png_set_unknown_chunks png16_png_set_unknown_chunks
#define png_set_user_limits png16_png_set_user_limits
#define png_set_user_transform_info png16_png_set_user_transform_info
#define png_set_write_fn png16_png_set_write_fn
#define png_set_write_status_fn png16_png_set_write_status_fn
#define png_set_write_user_transform_fn png16_png_set_write_user_transform_fn
#define png_sig_cmp png16_png_sig_cmp
#define png_start_read_image png16_png_start_read_image
#define png_warning png16_png_warning
#define png_write_chunk png16_png_write_chunk
#define png_write_chunk_data png16_png_write_chunk_data
#define png_write_chunk_end png16_png_write_chunk_end
#define png_write_chunk_start png16_png_write_chunk_start
#define png_write_end png16_png_write_end
#define png_write_flush png16_png_write_flush
#define png_write_image png16_png_write_image
#define png_write_info png16_png_write_info
#define png_write_info_before_PLTE png16_png_write_info_before_PLTE
#define png_write_png png16_png_write_png
#define png_write_row png16_png_write_row
#define png_write_rows png16_png_write_rows
#define png_write_sig png16_png_write_sig
#define png16_png_get_uint_32(buf) PNG_get_uint_32(buf)
#define png16_png_get_uint_16(buf) PNG_get_uint_16(buf)
#define png16_png_get_int_32(buf) PNG_get_int_32(buf)
#endif /* PNGLCONF_H */
