//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ppsspp.rc
//
#define IDS_DLGSETTINGSGENERAL          5
#define IDS_DLGSETTINGSGCMPATHS         6
#define IDS_DLGSETTINGSPLUGINS          7
#define IDS_ERRORNOGAMESFOUND           9
#define IDS_GAMELISTBANNER              10
#define IDS_GAMELISTCOMPANY             11
#define IDS_GAMELISTTITLE               12
#define IDS_GAMELISTNOTES               13
#define IDS_GAMELISTID                  14
#define IDS_GAMELISTSIZE                15
#define IDS_GAMELISTPATH                16
#define IDS_TIPS_LOADDOL                17
#define IDS_TIPS_LOADELF                18
#define IDS_TIPS_LOADGCM                19
#define IDS_TIPS_REFRESHGAMELIST        20
#define IDS_TIPS_RUN                    21
#define IDS_TIPS_PAUSE                  22
#define IDS_TIPS_STOP                   23
#define IDS_TIPS_FRAMEBUFFER            24
#define IDS_TIPS_HELP                   25
#define IDS_TIPS_CONFIGUREGFX           26
#define IDS_TIPS_CONFIGUREAUDIO         27
#define IDS_TIPS_CONFIGUREPAD           28
#define IDS_TIPS_CONFIGUREDVD           29
#define IDS_TIPS_SETTINGS               30
#define IDS_UNIMPLEMENTED               31
#define IDS_GAMELISTGENRE               32
#define IDS_APPNAME                     33
#define IDS_GAMELISTTYPE                34
#define IDR_MENU1                       101
#define IDD_DISASM                      102
#define IDC_FUNCTIONLIST                103
#define IDC_DISASMVIEW                  104
#define IDC_GOTOPC                      105
#define IDC_LEFTTABS                    106
#define IDC_RAM                         107
#define IDC_STEPOVER                    108
#define IDC_TABDATATYPE                 109
#define IDC_CALLSTACK                   110
#define IDC_UPDATECALLSTACK             111
#define ID_MEMVIEW_GOTOINDISASM         112
#define ID_DISASM_DYNARECRESULTS        113
#define IDI_PPSSPP                      115
#define IDD_CONFIG                      116
#define IDI_STOPDISABLE                 118
#define ID_DEBUG_DISASSEMBLY            119
#define ID_DEBUG_REGISTERS              120
#define ID_DEBUG_LOG                    121
#define ID_DEBUG_BREAKPOINTS            122
#define ID_FILE_LOAD_BIN                123
#define ID_FILE_LOAD_ISO                125
#define ID_FILE_LOADSTATEFILE           126
#define ID_FILE_SAVESTATEFILE           127
#define ID_EMULATION_RESET              130
#define IDD_ABOUTBOX                    133
#define ID_DEBUG_LOADMAPFILE            134
#define ID_CONFIG_RESOLUTION            141
#define ID_OPTIONS_FULLSCREEN           154
#define ID_OPTIONS_SETTINGS             155
#define ID_CPU_DYNAREC                  156
#define ID_CPU_INTERPRETER              157
#define ID_OPTIONS_SHOWERRORS           158
#define ID_PLUGINS_LOADDEFAULTPLUGINS   159
#define IDD_MEMORY                      160
#define ID_DEBUG_MEMORYVIEW             161
#define IDR_ACCELS                      162
#define ID_FILE_LOAD_ELF                165
#define ID_FILE_BOOTDVD                 166
#define ID_OPTIONS_ENABLEFRAMEBUFFER    167
#define IDR_POPUPMENUS                  169
#define ID_CHEATS_ACTIONREPLAYCODES     171
#define ID_DEBUG_MEMORYCHECKS           173
#define ID_DVD_INSERTISO                175
#define ID_FILE_LOAD_GCM                175
#define ID_DVD_EJECT                    176
#define ID_DVD_                         177
#define ID_DVD_OPENLID                  178
#define ID_PLUGINS_CONFIGUREGFXPLUGIN   179
#define ID_PLUGINS_CONFIGUREAUDIOPLUGIN 180
#define ID_PLUGINS_INPUTPLUGINSETTINGS  182
#define ID_PLUGINS_CONFIGUREPADPLUGIN   182
#define ID_DVD_BOOT                     183
#define ID_DVD_HLEBOOT                  184
#define ID_Menu185                      185
#define IDD_DIALOG2                     186
#define IDD_MEMORYSEARCH                187
#define ID_DEBUG_MEMORYSEARCH           188
#define ID_DEBUG_EXPERIMENT             189
#define IDR_MENU2                       190
#define ID_DISASM_GOTOINMEMORYVIEW      197
#define ID_DISASM_TOGGLEBREAKPOINT      198
#define ID_MEMVIEW_DUMP                 199
#define ID_OPTIONS_LOGGPFIFO            200
#define ID_VIEW_TOOLBAR202              202
#define ID_VIEW_STATUSBAR               203
#define ID_HELP_INDEX204                204
#define ID_HELP_                        206
#define ID_HELP_HOMEPAGE                208
#define ID_DEBUG_COMPILESIGNATUREFILE   209
#define ID_DEBUG_USESIGNATUREFILE       210
#define ID_DEBUG_UNLOADALLSYMBOLS       211
#define ID_DEBUG_RESETSYMBOLTABLE       212
#define IDI_STOP                        223
#define IDD_INPUTBOX                    226
#define IDD_VFPU                        231
#define IDD_CONTROLS                    232
#define IDC_GO                          1001
#define IDC_ADDRESS                     1002
#define IDC_DEBUG_COUNT                 1003
#define IDC_STOP                        1004
#define IDC_SKIP                        1005
#define IDC_MEMORY                      1006
#define IDC_SH4REGISTERS                1007
#define IDC_REGISTERS                   1007
#define IDC_BREAKPOINTS                 1008
#define IDC_STEP                        1009
#define IDC_UP                          1014
#define IDC_DIRTREE                     1014
#define IDC_DOWN                        1015
#define IDC_BREAKPOINTS_LIST            1015
#define IDC_ADD                         1016
#define IDC_BREAKPOINT_EDIT             1017
#define IDC_REMOVE                      1018
#define IDC_REMOVE_ALL                  1019
#define IDC_REGISTER_TAB                1019
#define IDC_HIDE                        1020
#define IDC_TOGGLEBREAKPOINT            1049
#define IDC_STAGE                       1059
#define IDC_MEMVIEW                     1069
#define IDC_GOTOLR                      1070
#define IDC_GOTOINT                     1071
#define IDC_MEMSORT                     1073
#define IDC_BACKWARDLINKS               1074
#define IDC_ALLFUNCTIONS                1075
#define IDC_RESULTS                     1093
#define IDC_SYMBOLS                     1097
#define IDC_X86ASM                      1098
#define IDC_INPUTBOX                    1098
#define IDC_MODENORMAL                  1099
#define IDC_MODESYMBOLS                 1100
#define IDC_LOG_SHOW                    1101
#define IDC_UPDATELOG                   1108
#define IDC_SETPC                       1118
#define IDC_UPDATEMISC                  1134
#define IDC_CODEADDRESS                 1135
#define IDC_BLOCKNUMBER                 1136
#define IDC_PREVBLOCK                   1138
#define IDC_REGIONS                     1142
#define IDC_REGLIST                     1146
#define IDC_VALUENAME                   1148
#define IDC_FILELIST                    1150
#define IDC_BROWSE                      1159
#define IDC_SHOWVFPU                    1161
#define IDC_LISTCONTROLS                1162
#define ID_FILE_BOOTISO                 40001
#define ID_FILE_EXIT                    40002
#define ID_CONFIG_SELECT_PLUGINS        40003
#define ID_BUTTON40013                  40013
#define ID_BUTTON40014                  40014
#define ID_BUTTON40015                  40015
#define ID_FILE_BOOTBIOS                40018
#define ID_COMPARE_STARTSERVER          40019
#define ID_COMPARE_CONNECTASCLIENT      40020
#define ID_CPU_COMPARE_CLOSECONNECTION  40022
#define ID_OPTIONS_EMULATESYSCALL       40023
#define ID_DEBUG_LOCATESYMBOLS          40025
#define ID_HELP_TOPICS                  40026
#define ID_PLUGINS_DVDPLUGINSETTINGS    40027
#define ID_PLUGINS_CONFIGUREDVDPLUGIN   40027
#define ID_DEBUG_SAVEMAPFILE            40028
#define ID_DEBUG_                       40029
#define ID_BUTTON40030                  40030
#define ID_BUTTON40031                  40031
#define ID_BUTTON40032                  40032
#define ID_BUTTON40033                  40033
#define ID_BUTTON40034                  40034
#define ID_BUTTON40035                  40035
#define ID_BUTTON40036                  40036
#define ID_BUTTON40037                  40037
#define ID_BUTTON40038                  40038
#define ID_BUTTON40039                  40039
#define ID_BUTTON40040                  40040
#define ID_BUTTON40041                  40041
#define ID_FILE_UNLOAD                  40043
#define ID_MEMCHECKS_TRIPLEMIRROR       40044
#define ID_MEMCHECKS_DUPLICATE          40045
#define ID_PLUGINS_CHOOSEPLUGINS        40048
#define ID_DISASM_ADDHLE                40050
#define ID_FUNCLIST_KILLFUNCTION        40051
#define ID_FILE_REFRESHGAMELIST         40053
#define ID_DISASM_RUNTOHERE             40054
#define ID_Menu                         40057
#define ID_MEMVIEW_COPYVALUE            40058
#define ID_DISASM_COPYINSTRUCTIONDISASM 40059
#define ID_DISASM_COPYINSTRUCTIONHEX    40060
#define ID_OPTIONS_CONFIGURATIONWIZARD  40064
#define ID_TOOLS_GCMSHRINKER            40065
#define ID_BUTTON40066                  40066
#define ID_GAMELIST_SHRINK              40067
#define ID_GAMELIST_PROPERTIES          40068
#define ID_GAMELIST_EXTRACT             40069
#define ID_GAMELIST_PLAY                40070
#define ID_EMULATION_SPEEDLIMIT         40071
#define ID_EMULATION_RUN                40072
#define ID_EMULATION_PAUSE              40073
#define ID_EMULATION_STOP               40074
#define ID_CPU_ENABLEDEBUGGING          40075
#define ID_FILE_LOAD                    40076
#define ID_OPTIONS_ENABLEDTKMUSIC       40078
#define ID_BUTTON40079                  40079
#define ID_HELP_ABOUT                   40080
#define ID_DISASM_FOLLOWBRANCH          40085
#define ID_OPTIONS_IGNOREILLEGALREADS   40086
#define ID_DISASM_COPYADDRESS           40087
#define ID_GAMELIST_OPENWITH            40090
#define ID_REGLIST_GOTOINMEMORYVIEW     40091
#define ID_REGLIST_COPYVALUE            40092
#define ID_REGLIST_COPY                 40093
#define ID_REGLIST_GOTOINDISASM         40094
#define ID_REGLIST_CHANGE               40095
#define ID_REGLIST_COPYVALUEATMEMOR     40100
#define ID_GAMELIST_EXPLORE             40101
#define ID_DEBUG_MEMORYVIEW2            40102
#define ID_DS_SHOWBGPALETTE             40103
#define ID_DS_SHOWBGPALETTE2            40104
#define ID_DISASM_RENAMEFUNCTION        40105
#define ID_DISASM_SETPCTOHERE           40107
#define ID_SYSTEM                       40108
#define ID_SYSTEM_DUMMY                 40109
#define ID_OPTIONS_DISPLAYRAWFRAMEBUFFER 40110
#define ID_HELP_OPENHTTP                40111
#define ID_HELP_OPENWEBSITE             40112
#define ID_OPTIONS_SCREEN1X             40113
#define ID_OPTIONS_MENUEDITOR           40114
#define ID_OPTIONS_SCREEN3X             40115
#define ID_OPTIONS_SCREEN4X             40116
#define ID_OPTIONS_SCREEN2X             40117
#define ID_OPTIONS_BUFFEREDRENDERING    40118
#define ID_EMULATION_FAST               40119
#define ID_EMULATION_FASTINTERPRETER    40120
#define ID_CPU_FASTINTERPRETER          40121
#define ID_OPTIONS_SHOWDEBUGSTATISTICS  40122
#define ID_OPTIONS_WIREFRAME            40123
#define ID_OPTIONS_HARDWARETRANSFORM    40124
#define ID_OPTIONS_FASTMEMORY           40125
#define IDC_STEPHLE                     40126
#define ID_OPTIONS_LINEARFILTERING      40127
#define ID_FILE_QUICKSAVESTATE          40128
#define ID_FILE_QUICKLOADSTATE          40129
#define ID_OPTIONS_CONTROLS             40130
#define ID_EMULATION_RUNONLOAD          40131
#define ID_DEBUG_DUMPNEXTFRAME          40132
#define ID_OPTIONS_SIMPLE2XSSAA         40133
#define ID_OPTIONS_USEVBO               40134
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        233
#define _APS_NEXT_COMMAND_VALUE         40135
#define _APS_NEXT_CONTROL_VALUE         1163
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
