// Used by ppsspp.rc
//

#define VS_USER_DEFINED                 100
#define IDR_MENU1                       101
#define IDD_DISASM                      102
#define IDC_FUNCTIONLIST                103
#define IDC_DISASMVIEW                  104
#define IDC_GOTOPC                      105
#define IDC_LEFTTABS                    106
#define IDC_RAM                         107
#define IDC_STEPOVER                    108
#define IDC_TABDATATYPE                 109
#define IDC_CALLSTACK                   110
#define ID_MEMVIEW_GOTOINDISASM         112
#define ID_DISASM_DYNARECRESULTS        113
#define IDI_PPSSPP                      115
#define IDD_CONFIG                      116
#define IDI_STOPDISABLE                 118
#define ID_DEBUG_DISASSEMBLY            119
#define ID_DEBUG_REGISTERS              120
#define WHEEL_DELTA                     120
#define ID_DEBUG_LOG                    121
#define ID_DEBUG_BREAKPOINTS            122
#define ID_FILE_LOADSTATEFILE           126
#define ID_FILE_SAVESTATEFILE           127
#define ID_EMULATION_RESET              130
#define IDD_ABOUTBOX                    133
#define ID_DEBUG_LOADMAPFILE            134
#define ID_CONFIG_RESOLUTION            141
#define ID_OPTIONS_FULLSCREEN           154
#define ID_OPTIONS_SETTINGS             155
#define ID_OPTIONS_SHOWERRORS           158
#define ID_PLUGINS_LOADDEFAULTPLUGINS   159
#define IDD_MEMORY                      160
#define ID_DEBUG_MEMORYVIEW             161
#define IDR_ACCELS                      162
#define ID_FILE_BOOTDVD                 166
#define ID_OPTIONS_ENABLEFRAMEBUFFER    167
#define IDR_POPUPMENUS                  169
#define ID_DEBUG_MEMORYCHECKS           173
#define IDD_DIALOG2                     186
#define IDD_MEMORYSEARCH                187
#define ID_DEBUG_MEMORYSEARCH           188
#define ID_DEBUG_EXPERIMENT             189
#define IDR_MENU2                       190
#define ID_DISASM_GOTOINMEMORYVIEW      197
#define ID_DISASM_TOGGLEBREAKPOINT      198
#define ID_MEMVIEW_DUMP                 199
#define ID_OPTIONS_LOGGPFIFO            200
#define ID_VIEW_TOOLBAR202              202
#define ID_VIEW_STATUSBAR               203
#define ID_HELP_INDEX204                204
#define ID_HELP_                        206
#define ID_HELP_HOMEPAGE                208
#define ID_DEBUG_COMPILESIGNATUREFILE   209
#define ID_DEBUG_USESIGNATUREFILE       210
#define ID_DEBUG_UNLOADALLSYMBOLS       211
#define ID_DEBUG_RESETSYMBOLTABLE       212
#define IDI_STOP                        223
#define IDD_INPUTBOX                    226
#define IDD_VFPU                        231
#define IDD_BREAKPOINT                  233
#define ID_FILE_LOAD_DIR                234
#define IDR_DEBUGACCELS                 237
#define ID_DEBUG_DISPLAYMEMVIEW         238
#define ID_DEBUG_DISPLAYBREAKPOINTLIST  239
#define ID_DEBUG_DISPLAYTHREADLIST      240
#define ID_DEBUG_DISPLAYSTACKFRAMELIST  241
#define ID_DEBUG_ADDBREAKPOINT          242
#define ID_DEBUG_STEPOVER               243
#define ID_DEBUG_STEPINTO               244
#define ID_DEBUG_RUNTOLINE              245
#define ID_DEBUG_STEPOUT                246
#define ID_DEBUG_DSIPLAYREGISTERLIST    247
#define ID_DEBUG_DSIPLAYFUNCTIONLIST    248
#define ID_MEMVIEW_COPYADDRESS          249
#define IDD_GEDEBUGGER                  250
#define IDD_TABDISPLAYLISTS             251
#define IDD_GEDBG_TAB_VALUES            252
#define IDD_DUMPMEMORY                  253
#define IDD_GEDBG_TAB_VERTICES          254
#define IDD_GEDBG_TAB_MATRICES          255

#define IDC_STOPGO                      1001
#define IDC_ADDRESS                     1002
#define IDC_DEBUG_COUNT                 1003
#define IDC_MEMORY                      1006
#define IDC_SH4REGISTERS                1007
#define IDC_REGISTERS                   1007
#define IDC_BREAKPOINTS                 1008
#define IDC_STEP                        1009
#define IDC_VERSION                     1010
#define IDC_UP                          1014
#define IDC_DOWN                        1015
#define IDC_BREAKPOINTS_LIST            1015
#define IDC_ADD                         1016
#define IDC_BREAKPOINT_EDIT             1017
#define IDC_REMOVE                      1018
#define IDC_REMOVE_ALL                  1019
#define IDC_REGISTER_TAB                1019
#define IDC_HIDE                        1020
#define IDC_TOGGLEBREAKPOINT            1049
#define IDC_STAGE                       1059
#define IDC_MEMVIEW                     1069
#define IDC_GOTOLR                      1070
#define IDC_GOTOINT                     1071
#define IDC_MEMSORT                     1073
#define IDC_ALLFUNCTIONS                1075
#define IDC_RESULTS                     1093
#define IDC_SYMBOLS                     1097
#define IDC_X86ASM                      1098
#define IDC_INPUTBOX                    1098
#define IDC_MODENORMAL                  1099
#define IDC_MODESYMBOLS                 1100
#define IDC_LOG_SHOW                    1101
#define IDC_UPDATELOG                   1108
#define IDC_SETPC                       1118
#define IDC_UPDATEMISC                  1134
#define IDC_CODEADDRESS                 1135
#define IDC_BLOCKNUMBER                 1136
#define IDC_PREVBLOCK                   1138
#define IDC_REGIONS                     1142
#define IDC_REGLIST                     1146
#define IDC_VALUENAME                   1148
#define IDC_FILELIST                    1150
#define IDC_BROWSE                      1159
#define IDC_SHOWVFPU                    1161
#define IDC_LISTCONTROLS                1162
#define IDC_FORCE_INPUT_DEVICE          1163
#define IDC_BREAKPOINTLIST              1164
#define IDC_DEBUGMEMVIEW                1165
#define IDC_BREAKPOINT_OK               1166
#define IDC_BREAKPOINT_CANCEL           1167
#define IDC_BREAKPOINT_ADDRESS          1168
#define IDC_BREAKPOINT_SIZE             1169
#define IDC_BREAKPOINT_CONDITION        1170
#define IDC_BREAKPOINT_EXECUTE          1171
#define IDC_BREAKPOINT_MEMORY           1172
#define IDC_BREAKPOINT_READ             1173
#define IDC_BREAKPOINT_WRITE            1174
#define IDC_BREAKPOINT_ENABLED          1175
#define IDC_BREAKPOINT_LOG              1176
#define IDC_BREAKPOINT_ONCHANGE         1177
#define IDC_THREADLIST                  1178
#define IDC_THREADNAME                  1179
#define IDC_DISASMSTATUSBAR             1180
#define IDC_STACKFRAMES                 1181
#define IDC_GEDBG_VALUES                1182
#define IDC_DUMP_USERMEMORY             1183
#define IDC_DUMP_VRAM                   1184
#define IDC_DUMP_SCRATCHPAD             1185
#define IDC_DUMP_CUSTOMRANGE            1186
#define IDC_DUMP_STARTADDRESS           1187
#define IDC_DUMP_SIZE                   1188
#define IDC_DUMP_FILENAME               1189
#define IDC_DUMP_BROWSEFILENAME         1190
#define IDC_GEDBG_FRAMEBUFADDR          1191
#define IDC_GEDBG_TEXADDR               1192
#define IDC_GEDBG_FBTABS                1193
#define IDC_GEDBG_VERTICES              1194
#define IDC_GEDBG_RAWVERTS              1195
#define IDC_GEDBG_MATRICES              1196

#define ID_SHADERS_BASE  5000

#define ID_FILE_EXIT                     40000
#define ID_DEBUG_SAVEMAPFILE             40001
#define ID_DISASM_ADDHLE                 40002
#define ID_FUNCLIST_KILLFUNCTION         40003
#define ID_DISASM_RUNTOHERE              40004
#define ID_MEMVIEW_COPYVALUE_8           40005
#define ID_DISASM_COPYINSTRUCTIONDISASM  40006
#define ID_DISASM_COPYINSTRUCTIONHEX     40007
#define ID_EMULATION_SPEEDLIMIT          40008
#define ID_TOGGLE_PAUSE                  40009
#define ID_EMULATION_STOP                40010
#define ID_FILE_LOAD                     40011
#define ID_HELP_ABOUT                    40012
#define ID_DISASM_FOLLOWBRANCH           40013
#define ID_DEBUG_IGNOREILLEGALREADS      40014
#define ID_DISASM_COPYADDRESS            40015
#define ID_REGLIST_GOTOINMEMORYVIEW      40016
#define ID_REGLIST_COPYVALUE             40017
#define ID_REGLIST_COPY                  40018
#define ID_REGLIST_GOTOINDISASM          40019
#define ID_REGLIST_CHANGE                40020
#define ID_DISASM_RENAMEFUNCTION         40021
#define ID_DISASM_SETPCTOHERE            40022
#define ID_HELP_OPENWEBSITE              40023
#define ID_OPTIONS_SCREENAUTO            40024
#define ID_OPTIONS_SCREEN1X              40025
#define ID_OPTIONS_SCREEN2X              40026
#define ID_OPTIONS_SCREEN3X              40027
#define ID_OPTIONS_SCREEN4X              40028
#define ID_OPTIONS_SCREEN5X              40029
#define ID_OPTIONS_HARDWARETRANSFORM     40030
#define IDC_STEPHLE                      40032
#define ID_OPTIONS_LINEARFILTERING       40033
#define ID_FILE_QUICKSAVESTATE           40034
#define ID_FILE_QUICKLOADSTATE           40035
#define ID_FILE_QUICKSAVESTATE_HC        40036
#define ID_FILE_QUICKLOADSTATE_HC        40037
#define ID_OPTIONS_CONTROLS              40038
#define ID_DEBUG_RUNONLOAD               40039
#define ID_DEBUG_DUMPNEXTFRAME           40040
#define ID_OPTIONS_VERTEXCACHE           40041
#define ID_OPTIONS_SHOWFPS               40042
#define ID_OPTIONS_STRETCHDISPLAY        40043
#define ID_OPTIONS_FRAMESKIP             40044
#define IDC_MEMCHECK                     40045
#define ID_FILE_MEMSTICK                 40046
#define ID_FILE_LOAD_MEMSTICK            40047
#define ID_EMULATION_SOUND               40048
#define ID_OPTIONS_MIPMAP                40049
#define ID_TEXTURESCALING_OFF            40050
#define ID_TEXTURESCALING_XBRZ           40051
#define ID_TEXTURESCALING_HYBRID         40052
#define ID_TEXTURESCALING_2X             40053
#define ID_TEXTURESCALING_3X             40054
#define ID_TEXTURESCALING_4X             40055
#define ID_TEXTURESCALING_5X             40056
#define ID_TEXTURESCALING_DEPOSTERIZE    40057
#define ID_TEXTURESCALING_BICUBIC        40058
#define ID_TEXTURESCALING_HYBRID_BICUBIC 40059
#define IDB_IMAGE_PSP                    40060
#define IDC_STATIC_IMAGE_PSP             40061
#define ID_CONTROLS_KEY_DISABLE          40062
#define ID_OPTIONS_TOPMOST               40063
#define ID_HELP_OPENFORUM                40064
#define ID_OPTIONS_VSYNC                 40065
#define ID_DEBUG_TAKESCREENSHOT          40066
#define ID_OPTIONS_TEXTUREFILTERING_AUTO 40067
#define ID_OPTIONS_NEARESTFILTERING      40068
#define ID_DISASM_DISASSEMBLETOFILE      40069
#define ID_OPTIONS_LINEARFILTERING_CG    40070
#define ID_DISASM_DISABLEBREAKPOINT      40071
#define ID_DISASM_THREAD_FORCERUN        40072
#define ID_DISASM_THREAD_KILL            40073
#define ID_FILE_SAVESTATE_NEXT_SLOT      40074
#define ID_FILE_SAVESTATE_NEXT_SLOT_HC   40075
#define ID_OPTIONS_READFBOTOMEMORYGPU	 40076
#define ID_OPTIONS_READFBOTOMEMORYCPU	 40077
#define ID_OPTIONS_NONBUFFEREDRENDERING  40078
#define ID_OPTIONS_FRAMESKIP_0           40079
#define ID_OPTIONS_FRAMESKIP_1           40080
#define ID_OPTIONS_FRAMESKIP_2           40081
#define ID_OPTIONS_FRAMESKIP_3           40082
#define ID_OPTIONS_FRAMESKIP_4           40083
#define ID_OPTIONS_FRAMESKIP_5           40084
#define ID_OPTIONS_FRAMESKIP_6           40085
#define ID_OPTIONS_FRAMESKIP_7           40086
#define ID_OPTIONS_FRAMESKIP_8           40087
#define ID_OPTIONS_FRAMESKIP_AUTO        40088
#define ID_OPTIONS_FRAMESKIPDUMMY        40089
#define ID_OPTIONS_RESOLUTIONDUMMY       40090
#define ID_DISASM_ASSEMBLE               40091
#define ID_DISASM_ADDNEWBREAKPOINT       40092
#define ID_DISASM_EDITBREAKPOINT         40093
#define ID_EMULATION_CHEATS              40096
#define ID_HELP_CHINESE_FORUM            40097
#define ID_OPTIONS_MORE_SETTINGS         40098
#define ID_FILE_SAVESTATE_SLOT_1         40099
#define ID_FILE_SAVESTATE_SLOT_2         40100
#define ID_FILE_SAVESTATE_SLOT_3         40101
#define ID_FILE_SAVESTATE_SLOT_4         40102
#define ID_FILE_SAVESTATE_SLOT_5         40103
#define ID_OPTIONS_WINDOW1X              40104
#define ID_OPTIONS_WINDOW2X              40105
#define ID_OPTIONS_WINDOW3X              40106
#define ID_OPTIONS_WINDOW4X              40107
#define ID_OPTIONS_WINDOW5X              40108
#define ID_OPTIONS_BUFFEREDRENDERING     40109
#define ID_DEBUG_SHOWDEBUGSTATISTICS     40110
#define ID_OPTIONS_SCREEN6X              40111
#define ID_OPTIONS_SCREEN7X              40112
#define ID_OPTIONS_SCREEN8X              40113
#define ID_OPTIONS_SCREEN9X              40114
#define ID_OPTIONS_SCREEN10X             40115
#define ID_DEBUG_GEDEBUGGER              40116
#define IDC_GEDBG_STEPDRAW               40117
#define IDC_GEDBG_RESUME                 40118
#define IDC_GEDBG_FRAME                  40119
#define IDC_GEDBG_MAINTAB                40120
#define IDC_GEDBG_TEX                    40121
#define IDC_GEDBG_STEP                   40122
#define IDC_GEDBG_LISTS_ALLLISTS         40123
#define IDC_GEDBG_LISTS_STACK            40124
#define IDC_GEDBG_LISTS_SELECTEDLIST     40125
#define ID_OPTIONS_FXAA                  40126
#define IDC_DEBUG_BOTTOMTABS             40127
#define ID_DEBUG_HIDEBOTTOMTABS          40128
#define ID_DEBUG_TOGGLEBOTTOMTABTITLES   40129
#define ID_GEDBG_SETSTALLADDR            40130
#define ID_GEDBG_GOTOPC                  40131
#define ID_GEDBG_GOTOADDR                40132
#define IDC_GEDBG_STEPTEX                40133
#define IDC_GEDBG_STEPFRAME              40134
#define IDC_GEDBG_BREAKTEX               40135
#define ID_OPTIONS_PAUSE_FOCUS           40136
#define ID_TEXTURESCALING_AUTO           40137
#define IDC_GEDBG_STEPPRIM               40138
#define ID_DISASM_ADDFUNCTION            40139
#define ID_DISASM_REMOVEFUNCTION         40140
#define ID_OPTIONS_LANGUAGE              40141
#define ID_MEMVIEW_COPYVALUE_16          40142
#define ID_MEMVIEW_COPYVALUE_32          40143
#define ID_EMULATION_SWITCH_UMD          40144
#define ID_DEBUG_EXTRACTFILE             40145
#define ID_OPTIONS_IGNOREWINKEY          40146
#define IDC_MODULELIST                   40147
#define IDC_GEDBG_TEXLEVELDOWN           40148
#define IDC_GEDBG_TEXLEVELUP             40149

// Dummy option to let the buffered rendering hotkey cycle through all the options.
#define ID_OPTIONS_BUFFEREDRENDERINGDUMMY 40500
#define IDC_STEPOUT                       40501
#define ID_HELP_BUYGOLD                   40502

#define IDC_STATIC                      -1

// Next default values for new objects
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        256
#define _APS_NEXT_COMMAND_VALUE         40150
#define _APS_NEXT_CONTROL_VALUE         1197
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
