# Core definitions
variables:
  GIT_SUBMODULE_STRATEGY: recursive

.core-defs:
  variables:
    CORENAME: ppsspp
    CORE_ARGS: -DLIBRETRO=ON
    MAKEFILE_PATH: libretro

include:
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'
    
# Stages for building
stages:
  - build-static

# Nintendo Switch - libnx
libretro-build-libnx-aarch64:
  extends:
    - .libretro-libnx-static-retroarch-master
    - .core-defs
    - .make-defs
