# libretro CI

.core-defs:
  variables:
    JNI_PATH: libretro
    CORENAME: ppsspp

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

stages:
  - build-prepare
  - build-shared
  - build-static
  - test

#Desktop
libretro-build-linux-x64:
  extends:
    - .core-defs
    - .libretro-linux-x64-make-default
  variables:
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile

libretro-build-windows-x64:
  extends:
    - .core-defs
    - .libretro-windows-x64-mingw-make-default
  variables:
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile
    
# Android
android-armeabi-v7a:
  extends:
    - .core-defs
    - .libretro-android-jni-armeabi-v7a

android-arm64-v8a:
  extends:
    - .core-defs
    - .libretro-android-jni-arm64-v8a

android-x86_64:
  extends:
    - .core-defs
    - .libretro-android-jni-x86_64
    
android-x86:
  extends:
    - .core-defs
    - .libretro-android-jni-x86
