# libavutil source files (all platforms)
set(LIBAVUTIL_SOURCE_FILES
	${LIBAVUTIL_SRC_DIR}/adler32.c
	${LIBAVUTIL_SRC_DIR}/aes_ctr.c
	${LIBAVUTIL_SRC_DIR}/aes.c
	${LIBAVUTIL_SRC_DIR}/audio_fifo.c
	${LIBAVUTIL_SRC_DIR}/avstring.c
	${LIBAVUTIL_SRC_DIR}/base64.c
	${LIBAVUTIL_SRC_DIR}/blowfish.c
	${LIBAVUTIL_SRC_DIR}/bprint.c
	${LIBAVUTIL_SRC_DIR}/buffer.c
	${LIBAVUTIL_SRC_DIR}/camellia.c
	${LIBAVUTIL_SRC_DIR}/cast5.c
	${LIBAVUTIL_SRC_DIR}/channel_layout.c
	${LIBAVUTIL_SRC_DIR}/color_utils.c
	${LIBAVUTIL_SRC_DIR}/cpu.c
	${LIBAVUTIL_SRC_DIR}/crc.c
	${LIBAVUTIL_SRC_DIR}/des.c
	${LIBAVUTIL_SRC_DIR}/dict.c
	${LIBAVUTIL_SRC_DIR}/display.c
	${LIBAVUTIL_SRC_DIR}/downmix_info.c
	${LIBAVUTIL_SRC_DIR}/error.c
	${LIBAVUTIL_SRC_DIR}/eval.c
	${LIBAVUTIL_SRC_DIR}/fifo.c
	${LIBAVUTIL_SRC_DIR}/file_open.c
	${LIBAVUTIL_SRC_DIR}/file.c
	${LIBAVUTIL_SRC_DIR}/fixed_dsp.c
	${LIBAVUTIL_SRC_DIR}/float_dsp.c
	${LIBAVUTIL_SRC_DIR}/frame.c
	${LIBAVUTIL_SRC_DIR}/hash.c
	${LIBAVUTIL_SRC_DIR}/hmac.c
	${LIBAVUTIL_SRC_DIR}/imgutils.c
	${LIBAVUTIL_SRC_DIR}/integer.c
	${LIBAVUTIL_SRC_DIR}/intmath.c
	${LIBAVUTIL_SRC_DIR}/lfg.c
	${LIBAVUTIL_SRC_DIR}/lls.c
	${LIBAVUTIL_SRC_DIR}/log.c
	${LIBAVUTIL_SRC_DIR}/log2_tab.c
	${LIBAVUTIL_SRC_DIR}/mastering_display_metadata.c
	${LIBAVUTIL_SRC_DIR}/mathematics.c
	${LIBAVUTIL_SRC_DIR}/md5.c
	${LIBAVUTIL_SRC_DIR}/mem.c
	${LIBAVUTIL_SRC_DIR}/murmur3.c
	${LIBAVUTIL_SRC_DIR}/opt.c
	${LIBAVUTIL_SRC_DIR}/parseutils.c
	${LIBAVUTIL_SRC_DIR}/pixdesc.c
	${LIBAVUTIL_SRC_DIR}/pixelutils.c
	${LIBAVUTIL_SRC_DIR}/random_seed.c
	${LIBAVUTIL_SRC_DIR}/rational.c
	${LIBAVUTIL_SRC_DIR}/rc4.c
	${LIBAVUTIL_SRC_DIR}/reverse.c
	${LIBAVUTIL_SRC_DIR}/ripemd.c
	${LIBAVUTIL_SRC_DIR}/samplefmt.c
	${LIBAVUTIL_SRC_DIR}/sha.c
	${LIBAVUTIL_SRC_DIR}/sha512.c
	${LIBAVUTIL_SRC_DIR}/stereo3d.c
	${LIBAVUTIL_SRC_DIR}/tea.c
	${LIBAVUTIL_SRC_DIR}/threadmessage.c
	${LIBAVUTIL_SRC_DIR}/time.c
	${LIBAVUTIL_SRC_DIR}/timecode.c
	${LIBAVUTIL_SRC_DIR}/tree.c
	${LIBAVUTIL_SRC_DIR}/twofish.c
	${LIBAVUTIL_SRC_DIR}/utils.c
	${LIBAVUTIL_SRC_DIR}/xga_font_data.c
	${LIBAVUTIL_SRC_DIR}/xtea.c
)

set(LIBAVUTIL_HEADERS
	${LIBAVUTIL_SRC_DIR}/adler32.h
	${LIBAVUTIL_SRC_DIR}/aes.h
	${LIBAVUTIL_SRC_DIR}/aes_ctr.h
	${LIBAVUTIL_SRC_DIR}/attributes.h
	${LIBAVUTIL_SRC_DIR}/audio_fifo.h
	${LIBAVUTIL_SRC_DIR}/avassert.h
	${LIBAVUTIL_SRC_DIR}/avstring.h
	${LIBAVUTIL_SRC_DIR}/avutil.h
	${LIBAVUTIL_SRC_DIR}/base64.h
	${LIBAVUTIL_SRC_DIR}/blowfish.h
	${LIBAVUTIL_SRC_DIR}/bprint.h
	${LIBAVUTIL_SRC_DIR}/bswap.h
	${LIBAVUTIL_SRC_DIR}/buffer.h
	${LIBAVUTIL_SRC_DIR}/cast5.h
	${LIBAVUTIL_SRC_DIR}/camellia.h
	${LIBAVUTIL_SRC_DIR}/channel_layout.h
	${LIBAVUTIL_SRC_DIR}/common.h
	${LIBAVUTIL_SRC_DIR}/cpu.h
	${LIBAVUTIL_SRC_DIR}/crc.h
	${LIBAVUTIL_SRC_DIR}/des.h
	${LIBAVUTIL_SRC_DIR}/display.h
	${LIBAVUTIL_SRC_DIR}/downmix_info.h
	${LIBAVUTIL_SRC_DIR}/error.h
	${LIBAVUTIL_SRC_DIR}/eval.h
	${LIBAVUTIL_SRC_DIR}/fifo.h
	${LIBAVUTIL_SRC_DIR}/file.h
	${LIBAVUTIL_SRC_DIR}/frame.h
	${LIBAVUTIL_SRC_DIR}/hash.h
	${LIBAVUTIL_SRC_DIR}/hmac.h
	${LIBAVUTIL_SRC_DIR}/imgutils.h
	${LIBAVUTIL_SRC_DIR}/intfloat.h
	${LIBAVUTIL_SRC_DIR}/intreadwrite.h
	${LIBAVUTIL_SRC_DIR}/lfg.h
	${LIBAVUTIL_SRC_DIR}/log.h
	${LIBAVUTIL_SRC_DIR}/macros.h
	${LIBAVUTIL_SRC_DIR}/mathematics.h
	${LIBAVUTIL_SRC_DIR}/mastering_display_metadata.h
	${LIBAVUTIL_SRC_DIR}/md5.h
	${LIBAVUTIL_SRC_DIR}/mem.h
	${LIBAVUTIL_SRC_DIR}/motion_vector.h
	${LIBAVUTIL_SRC_DIR}/murmur3.h
	${LIBAVUTIL_SRC_DIR}/dict.h
	${LIBAVUTIL_SRC_DIR}/opt.h
	${LIBAVUTIL_SRC_DIR}/parseutils.h
	${LIBAVUTIL_SRC_DIR}/pixdesc.h
	${LIBAVUTIL_SRC_DIR}/pixelutils.h
	${LIBAVUTIL_SRC_DIR}/pixfmt.h
	${LIBAVUTIL_SRC_DIR}/random_seed.h
	${LIBAVUTIL_SRC_DIR}/rc4.h
	${LIBAVUTIL_SRC_DIR}/replaygain.h
	${LIBAVUTIL_SRC_DIR}/rational.h
	${LIBAVUTIL_SRC_DIR}/ripemd.h
	${LIBAVUTIL_SRC_DIR}/samplefmt.h
	${LIBAVUTIL_SRC_DIR}/sha.h
	${LIBAVUTIL_SRC_DIR}/sha512.h
	${LIBAVUTIL_SRC_DIR}/stereo3d.h
	${LIBAVUTIL_SRC_DIR}/threadmessage.h
	${LIBAVUTIL_SRC_DIR}/time.h
	${LIBAVUTIL_SRC_DIR}/timecode.h
	${LIBAVUTIL_SRC_DIR}/timestamp.h
	${LIBAVUTIL_SRC_DIR}/tree.h
	${LIBAVUTIL_SRC_DIR}/twofish.h
	${LIBAVUTIL_SRC_DIR}/version.h
	${LIBAVUTIL_SRC_DIR}/xtea.h
	${LIBAVUTIL_SRC_DIR}/tea.h
	${CMAKE_CURRENT_BINARY_DIR}/libavutil/ffversion.h 
	${CMAKE_CURRENT_BINARY_DIR}/libavutil/avconfig.h 
)

# Experimental addition to troubleshoot stubborn builds that inject ARCH_X86
if (ARCH_X86)
	list(APPEND LIBAVUTIL_SOURCE_FILES ${LIBAVUTIL_SRC_DIR}/x86/cpu.c)
endif()
