// Header generated by atlastool from atlasscript.txt (hrydgard@gmail.com)

#pragma once
#include "gfx/texture_atlas.h"

// FONTS_ui
#define UBUNTU24 0
#define UBUNTUBOLD24 1
#define UBUNTU48 2


// IMAGES_ui
#define SOLIDWHITE 0
#define I_CROSS 1
#define I_CIRCLE 2
#define I_SQUARE 3
#define I_TRIANGLE 4
#define I_SELECT 5
#define I_START 6
#define I_ARROW 7
#define I_DIR 8
#define I_ROUND 9
#define I_STICK 10
#define I_SHOULDER 11
#define I_RECT 12
#define I_STICKBG 13
#define I_BG 14
#define I_L 15
#define I_R 16
#define I_BUTTON 17
#define I_BUTTON_SELECTED 18
#define I_ACTIVE_ITEM 19
#define I_INACTIVE_ITEM 20
#define I_ICON_UMD 21
#define I_ICON_FOLDER 22
#define I_ICON_EXE 23


extern const Atlas ui_atlas;
extern const AtlasImage ui_images[24];
