name: Bug, crash, or compatibility issue
description: Choose this if something doesn't work and no other template applies.
body:
  - type: markdown
    attributes:
      value: |
        Want the issue fixed faster?  Check the wiki for tips:
        https://github.com/hrydgard/ppsspp/wiki/How-to-report-an-issue-properly

  - type: input
    id: game
    validations:
      required: true
    attributes:
      label: Game or games this happens in
      placeholder: ULUS-10336 - Crisis Core
      description: >
        Shown in the title bar, logs, and long press on the game icon.  If it's outside a game, put 'None.'

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: What area of the game / PPSSPP
      placeholder: |
        When I equip a Mythril Bangle, a blue screen appears and it says the game crashed.

        Here's a screenshot of the blue screen:
        [upload screenshot]

        Here's a my savedata with a Mythril Bangle not equipped yet:
        [upload zip of savedata]
      description: >
        Try to explain so someone else could do the same thing.  Upload savedata if possible to make it easier to reproduce.

  - type: textarea
    id: desired
    validations:
      required: true
    attributes:
      label: What should happen
      placeholder: |
        The Mythril Bangle should be equipped without crashing.

        My friend also tried this on their actual PSP, and it worked fine.  Here's a screenshot right after equipping frmo my savedata:
        [upload photo]
      description: >
        If it's a crash, just say "It shouldn't crash."  For more complex bugs, it helps to explain what should happen as it's not always obvious.

  - type: textarea
    id: logs
    attributes:
      label: Logs
      placeholder: '[drag files here...]'
      description: |
        Upload logs if possible (use DebugLog.bat on Windows or [adb logcat][] on Android.)
        [adb logcat]: https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

  - type: markdown
    attributes:
      value: |
        ## Your device

        If you're not sure about any of these questions, check Settings -> Tools -> System Information.

  - type: dropdown
    id: platform
    validations:
      required: true
    attributes:
      label: Platform
      options:
        - Android
        - Windows
        - libretro / Retroarch
        - iOS
        - Switch
        - Raspberry Pi
        - Linux / BSD
        - macOS
        - UWP / Xbox
        - Other

  - type: input
    id: device
    validations:
      required: true
    attributes:
      label: Mobile device model or graphics card (GPU)
      placeholder: Google Pixel 4a or NVIDIA GeForce GTX 1080Ti
      description: >
        If you don't know, copy what's under 'Driver version' in System Information.

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: PPSSPP version affected
      placeholder: v2.0.0-999-gabcdef123
      description: >
        Shown on the main screen of PPSSPP where games are listed.

  - type: input
    id: workingversion
    attributes:
      label: Last working version
      placeholder: v2.0.0-500-g321fedcba
      description: >
        If it worked before, it's usually easier to narrow down a fix.

  - type: dropdown
    id: gpubackend
    validations:
      required: true
    attributes:
      label: Graphics backend (3D API)
      options:
        - Vulkan
        - OpenGL / GLES
        - Direct3D 11
        - Direct3D 9
        - Other

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: "Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed."
          required: true
        - label: "[Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue."
          required: true
        - label: "Try resetting settings or older versions and include if the issue is related."
        - label: "Try without any cheats and without loading any save states."
        - label: "Include logs or screenshots of issue."
