name: Graphics or rendering issue
description: Choose when something is drawing wrong.
body:
  - type: markdown
    attributes:
      value: |
        Want the issue fixed faster?  Check the wiki for tips:
        https://github.com/hrydgard/ppsspp/wiki/How-to-report-an-issue-properly

  - type: input
    id: game
    validations:
      required: true
    attributes:
      label: Game or games this happens in
      placeholder: ULUS-10336 - Crisis Core
      description: >
        Shown in the title bar, logs, and long press on the game icon.

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: What area of the game
      placeholder: 'At the start of Chapter 3, in Sector 8.  Right outside the briefing room, the save point looks garbled.'
      description: >
        If it happens from the start of any game, just say "After new game".  Try to explain so someone else could do the same thing.

  - type: textarea
    id: problem
    validations:
      required: true
    attributes:
      label: What happens
      placeholder: |
        The save point seems to be moving like it should, but the colors all all wrong - it shouldn't be red.  Here's what it looks like:
        [upload screenshot]

        Even when I step into it, it turned black which it shouldn't:
        [upload screenshot]
      description: >
        Include screenshots, they're important.  But explain what's wrong in the screenshot - it may not be obvious to others.

  - type: textarea
    id: desired
    validations:
      required: true
    attributes:
      label: What should happen
      placeholder: |
        The save point should look like it does in other places:
        [upload screenshot]

        My friend also tried this on their actual PSP, where it looks right:
        [upload photo]
      description: >
        If you can include a screenshot (from a previous version, another emulator, or a PSP), it helps a lot.  But explaining how it should look helps a lot too.

  - type: markdown
    attributes:
      value: |
        Including a frame capture (or multiple) usually helps a lot.  These are like 3D screenshots for PPSSPP.  Instructions are available [on the wiki][] to create one.
        [on the wiki]: https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

  - type: textarea
    id: screenshots
    attributes:
      label: GE frame capture
      placeholder: '[drag files here...]'
      description: >
        You can upload the frame capture or captures as a zip file.  Make sure the issue is visible on screen during the capture.

  - type: markdown
    attributes:
      value: |
        ## Your device

        If you're not sure about any of these questions, check Settings -> Tools -> System Information.

  - type: dropdown
    id: platform
    validations:
      required: true
    attributes:
      label: Platform
      options:
        - Android
        - Windows
        - libretro / Retroarch
        - iOS
        - Switch
        - Raspberry Pi
        - Linux / BSD
        - macOS
        - UWP / Xbox
        - Other

  - type: input
    id: device
    validations:
      required: true
    attributes:
      label: Mobile device model or graphics card (GPU)
      placeholder: Google Pixel 4a or NVIDIA GeForce GTX 1080Ti
      description: >
        If you don't know, copy what's under 'Driver version' in System Information.

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: PPSSPP version affected
      placeholder: v2.0.0-999-gabcdef123
      description: >
        Shown on the main screen of PPSSPP where games are listed.

  - type: input
    id: workingversion
    attributes:
      label: Last working version
      placeholder: v2.0.0-500-g321fedcba
      description: >
        If it worked before, it's usually easier to narrow down a fix.

  - type: dropdown
    id: gpubackend
    validations:
      required: true
    attributes:
      label: Graphics backend (3D API)
      options:
        - Vulkan
        - OpenGL / GLES
        - Direct3D 11
        - Direct3D 9
        - Other

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: "Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed."
          required: true
        - label: "[Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue."
          required: true
        - label: "Try resetting settings or older versions and include if the issue is related."
        - label: "Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)"
        - label: "Include logs or screenshots of issue."
