.TH "PPSSPP" "1" "July 2014" "PPSSPP" "User Commands"
.SH "NAME"
PPSSPP \- PSP emulator.
.SH "SYNOPSIS"
ppsspp
.SH "DESCRIPTION"
PPSSPP can run your PSP games on your PC in full HD resolution. It can even upscale textures that would otherwise be too blurry as they were made for the small screen of the original PSP.
.PP
See http://www.ppsspp.org/ for more information.
