// Header generated by atlastool from atlasscript.txt (hrydgard@gmail.com)

#pragma once
#include "gfx/texture_atlas.h"

// FONTS_ui
#define UBUNTU24 0


// IMAGES_ui
#define I_SOLIDWHITE 0
#define I_CROSS 1
#define I_CIRCLE 2
#define I_SQUARE 3
#define I_TRIANGLE 4
#define I_CROSS1 5
#define I_SQUARE1 6
#define I_TRIANGLE1 7
#define I_STAR 8
#define I_GC 9
#define I_EYE 10
#define I_SELECT 11
#define I_START 12
#define I_ARROW 13
#define I_ARROW1 14
#define I_ARROW2 15
#define I_ARROW3 16
#define I_DIR 17
#define I_ROUND 18
#define I_RECT 19
#define I_STICK 20
#define I_STICK_BG 21
#define I_SHOULDER 22
#define I_DIR_LINE 23
#define I_ROUND_LINE 24
#define I_RECT_LINE 25
#define I_SHOULDER_LINE 26
#define I_STICK_LINE 27
#define I_STICK_BG_LINE 28
#define I_CHECKEDBOX 29
#define I_BG1 30
#define I_BG2 31
#define I_BG3 32
#define I_BG_GOLD 33
#define I_L 34
#define I_R 35
#define I_DROP_SHADOW 36
#define I_LINES 37
#define I_GRID 38
#define I_LOGO 39
#define I_ICON 40
#define I_ICONGOLD 41
#define I_FOLDER 42
#define I_UP_DIRECTORY 43


extern const Atlas ui_atlas;
extern const AtlasImage ui_images[44];
