// Header generated by atlastool from ppge_atlasscript.txt (hrydgard@gmail.com)

#pragma once
#include "gfx/texture_atlas.h"

// FONTS_ppge
#define UBUNTU24 0


// IMAGES_ppge
#define I_CROSS 0
#define I_CIRCLE 1
#define I_SQUARE 2
#define I_TRIANGLE 3


extern const Atlas ppge_atlas;
extern const AtlasImage ppge_images[4];
